version: '3.8'

services:
  scheduler:
    build: .
    container_name: instagram-scheduler
    restart: unless-stopped
    # Add init for proper process management
    init: true
    environment:
      - NODE_ENV=production
      - TZ=Asia/Kolkata
      # Container-specific environment variables
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    env_file:
      - .env
    volumes:
      - ./generated:/app/generated
      - ./logs:/app/logs
      # Add tmpfs for better performance
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
    # Resource limits to ensure stable Puppeteer operation
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '0.75'
        reservations:
          memory: 768M
          cpus: '0.5'
    # Increased shared memory size for Chromium stability
    shm_size: 512m
    # Security options for better browser operation
    security_opt:
      - seccomp:unconfined
    # Health check using process monitoring instead of HTTP
    healthcheck:
      test: ["CMD", "pgrep", "-f", "schedule-posts", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s