version: '3.8'

services:
  scheduler:
    build: .
    container_name: instagram-scheduler
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Kolkata
    env_file:
      - .env
    volumes:
      - ./generated:/app/generated
      - ./logs:/app/logs
    # Resource limits to ensure stable Puppeteer operation
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    # Shared memory size for Chromium
    shm_size: 256m