version: '3.8'

services:
  scheduler:
    build: .
    container_name: instagram-scheduler
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Kolkata
    env_file:
      - .env
    volumes:
      - ./generated:/app/generated
      - ./logs:/app/logs